- name: Install git
  become: true
  yum:
          name: git
          state: latest

- name: Clone dotfiles
  git:
          repo: https://github.com/jundi/dotfiles.git
          dest: ~/.config/dotfiles

- name: Include dotfiles
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    force: no
  with_items:
          - { src: 'templates/gitconfig', dest: '~/.gitconfig' }
          - { src: 'templates/bash_profile', dest: '~/.bash_profile' }
          - { src: 'templates/bashrc', dest: '~/.bashrc' }
          - { src: 'templates/Xmodmap', dest: '~/.Xmodmap' }
          - { src: 'templates/xprofile', dest: '~/.xprofile' }
          - { src: 'templates/xsession', dest: '~/.xsession' }
