---
- name: Install epel-release repository
  become: true
  yum:
    name: epel-release
    state: latest

- name: Install bash completion
  become: true
  yum:
    name: bash-completion-extras

- name: Install git
  become: true
  yum:
    name: git
    state: latest

- name: Install Neovim
  become: true
  yum:
    name:
      - neovim
      - python36-neovim
    state: latest

- name: Install Python2 setuptools (required for pip3)
  become: true
  yum:
    name: python-setuptools
    state: latest

- name: Enable clipboard syncronization over SSH
  yum:
    name:
      - xorg-x11-xauth
      - xsel
    state: latest
