---
- name: Install epel-release repository
  become: true
  yum:
    name: epel-release
    state: latest

- name: Install bash completion
  become: true
  yum:
    name: bash-completion-extras

- name: Install git
  become: true
  yum:
    name: git
    state: latest

- name: Install xorg-x11-xauth
  become: true
  yum:
    name: xorg-x11-xauth
    state: latest

- name: Install Neovim
  become: true
  yum:
    name:
      - neovim
      - python36-neovim
    state: latest
