---
- name: Install epel-release repo
  become: true
  yum:
    name: epel-release

- name: Install dev tools
  become: true
  yum:
    name:
      - bash-completion-extras
      - git
      - neovim
      - python36-neovim
      - python36-virtualenv
      - screen
      - htop
    state: latest

- name: Install Python2 setuptools (required for pip3)
  become: true
  yum:
    name: python-setuptools
    state: latest

- name: Enable clipboard syncronization over SSH
  become: true
  yum:
    name:
      - xorg-x11-xauth
      - xsel
    state: latest
