---
- name: Install git
  become: true
  dnf:
    name: git
    state: latest

- name: Install epel-release repository
  become: true
  dnf:
    name: epel-release
    state: latest

- name: Install Neovim
  become: true
  dnf:
    name:
      - neovim
    state: latest

- name: Enable clipboard syncronization over SSH
  become: true
  yum:
    name:
      - xorg-x11-xauth
      - xsel
    state: latest

- name: Install misc software
  yum:
    name:
      - tig
      - tree

- name: Install more misc software
  pip:
    name:
      - ranger-fm
    extra_args: --user
    executable: pip3
