---
- name: Install git
  become: true
  dnf:
    name: git
    state: latest

- name: Install epel-release repository
  become: true
  dnf:
    name: epel-release
    state: latest

- name: Install Neovim
  become: true
  dnf:
    name:
      - neovim
    state: latest

- name: Enable cliboard syncronization over SSH
  yum:
    name:
      - xorg-x11-xauth
      - xsel
    state: latest
