---
- name: Install dev tools
  become: true
  yum:
    name:
      - epel-release
      - git
      - tig
      - tree
      - python3-pip
      - wget
      - neovim

- name: Install dev tools from PyPi
  pip:
    name:
      - ranger-fm
    extra_args: --user
    executable: pip3

- name: Enable clipboard syncronization over SSH
  become: true
  yum:
    name:
      - xorg-x11-xauth
      - xsel
    state: latest
