---
- name: Create directory for custom binaries
  file:
    path: ~/.opt/bin/
    state: directory

- name: Symlink vim to neovim
  file:
    path: ~/.opt/bin/vim
    src: /usr/bin/nvim
    state: link
    force: true

- name: Create .config directory
  file:
    path: ~/.config
    state: directory

- name: Clone vimfiles repo
  git:
    repo: https://github.com/jundi/vimfiles.git
    dest: ~/.config/nvim

- name: Create directory for plugins
  file:
    path: ~/.config/nvim/autoload
    state: directory

- name: Install plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.config/nvim/autoload/plug.vim

- name: Install plugins
  command: nvim -u NORC '+source ~/.config/nvim/init.vim' +PlugUpdate +UpdateRemotePlugins +qall

- name: Add vimpager executables
  file:
    path: ~/.opt/bin/vimpager
    src: ~/.vim/plugged/vimpager/vimpager
    state: link
    force: true

- name: Create directory for vim backups
  file:
    path: ~/.vimbackup
    state: directory

- name: Symlink neovim configuration directory to ~/.vim
  file:
    src: ~/.config/nvim
    path: ~/.vim
    state: link
    force: true

- name: Install completion and linting software
  pip:
    name:
      - ansible-lint
      - pylint
      - jedi
      - rstcheck
      - pylint-venv
      - flake8
      - pydocstyle
      - yamllint
      - yapf
    extra_args: --user
    executable: pip3
